[build]
  command = "npm run netlify-build"
  publish = ".next"

[build.environment]
  NETLIFY_NEXT_PLUGIN_SKIP = "true"
  DISABLE_ESLINT_PLUGIN = "true"
  NEXT_DISABLE_ESLINT = "1"
  NEXT_DISABLE_TYPESCRIPT = "1"
  CI = "false"

[[plugins]]
  package = "@netlify/plugin-nextjs" 